export const GET_REQUEST_DATA = 'GET_REQUEST_DATA';
export const RECENTLY_ViEWED_DATA = 'RECENTLY_ViEWED_DATA';
export const ADD_CART_DATA = 'ADD_CART_DATA';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const ADD_PRODUCT_FREQUENCY = 'ADD_PRODUCT_FREQUENCY';
export const PLACED_ORDER = 'PLACED_ORDER';
export const ADD_CURRENT_USER = 'ADD_CURRENT_USER';